Fix crash with World Energy Exporter
Putting a card into the world energy exporter caused this error ```
java.lang.ClassCastException: org.cyclops.integratedtunnels.part.PartStateWorld cannot be cast to org.cyclops.integratedtunnels.part.PartStateEnergy
	at org.cyclops.integratedtunnels.part.aspect.TunnelAspectWriteBuilders$World$Energy.lambda$static$0(TunnelAspectWriteBuilders.java:1052)
	at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.write(AspectBuilder.java:428)
	at org.cyclops.integrateddynamics.part.aspect.write.AspectWriteBase.update(AspectWriteBase.java:57)
	at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.update(AspectBuilder.java:451)
	at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:96)
	at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:48)
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:134)
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:408)
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_608_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```
This change keeps it from crashing though I'm not sure how to actually test if it's behaving as intended, but not crashing is an improvement